/**
 * W44 — Design outcome cards (20).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const designOutcomeCards: OutcomeCard[] = [
  {
    id: "des-create-hero",
    department: "design",
    label: "Create a hero image for my site",
    seed: "Create a hero image for my website that fits my brand colors and feel. Make it specific to what we sell, not generic stock-photo energy.",
    tags: ["one-shot", "creative"],
    weight: 1.5,
  },
  {
    id: "des-design-logo",
    department: "design",
    label: "Design logo directions to react to",
    seed: "Design three logo directions for my business to react to. Ground each in my brand personality and tell me what each direction signals.",
    tags: ["one-shot", "creative"],
    weight: 1.0,
  },
  {
    id: "des-build-brandguide",
    department: "design",
    label: "Build a one-page brand guide",
    seed: "Build a one-page visual brand guide from what you know about my business — colors, type, spacing, and the feel we always aim for.",
    tags: ["one-shot", "creative"],
    weight: 1.5,
  },
  {
    id: "des-create-social",
    department: "design",
    label: "Create on-brand social graphics",
    seed: "Create a set of social graphics in my brand style for this week's posts. Keep them consistent enough to be recognizable in the feed.",
    tags: ["weekly", "creative", "content"],
    weight: 1.5,
  },
  {
    id: "des-design-deck",
    department: "design",
    label: "Design a pitch deck that looks expensive",
    seed: "Design the visual system for my pitch deck — layout, type hierarchy, and slide patterns that make the story feel inevitable.",
    tags: ["one-shot", "creative", "b2b"],
    weight: 1.0,
  },
  {
    id: "des-review-website",
    department: "design",
    label: "Review my website's first impression",
    seed: "Review my website like a first-time visitor with five seconds to spare. Tell me what reads instantly, what confuses, and what to fix first.",
    tags: ["one-shot", "creative", "growth"],
    weight: 1.0,
  },
  {
    id: "des-create-thumbnail",
    department: "design",
    label: "Create a thumbnail that earns the click",
    seed: "Create a video thumbnail that earns the click without lying about the content. Big readable promise, my brand colors, one focal point.",
    tags: ["one-shot", "creative", "content"],
    weight: 1.0,
  },
  {
    id: "des-design-card",
    department: "design",
    label: "Design a business card",
    seed: "Design a business card that matches my brand and doesn't look like a template. Front and back, with the details people actually need.",
    tags: ["one-shot", "creative"],
    weight: 0.5,
  },
  {
    id: "des-map-userflow",
    department: "design",
    label: "Map the user flow through my site",
    seed: "Map how a visitor moves through my site from landing to action. Mark the steps where people likely hesitate and what would remove the friction.",
    tags: ["one-shot", "creative", "growth"],
    weight: 0.5,
  },
  {
    id: "des-create-banners",
    department: "design",
    label: "Create banners for every platform",
    seed: "Create a matched set of banner images for my profiles and pages, sized for each platform, all clearly the same brand.",
    tags: ["one-shot", "creative"],
    weight: 1.0,
  },
  {
    id: "des-refine-palette",
    department: "design",
    label: "Refine my brand colors",
    seed: "Refine my brand color palette. Keep what's recognizable, fix what clashes, and give me the exact values with usage notes.",
    tags: ["one-shot", "creative"],
    weight: 0.5,
  },
  {
    id: "des-design-menu",
    department: "design",
    label: "Design a menu that sells the kitchen",
    seed: "Design my menu so the dishes we want to sell get the attention. Layout, sections, and pricing presentation that guide the order.",
    tags: ["one-shot", "creative", "restaurants"],
    weight: 0.5,
  },
  {
    id: "des-create-productshots",
    department: "design",
    label: "Create product shots without a studio",
    seed: "Create polished product images for what we sell — clean backgrounds, consistent lighting and angles across the set, true to the product.",
    tags: ["one-shot", "creative", "ecommerce"],
    weight: 1.0,
  },
  {
    id: "des-review-checkout",
    department: "design",
    label: "Review my checkout for drop-off",
    seed: "Review my checkout or booking flow for the moments people abandon. Walk it step by step and flag every point of doubt or effort.",
    tags: ["one-shot", "creative", "ecommerce", "revenue"],
    weight: 0.5,
  },
  {
    id: "des-design-emailheader",
    department: "design",
    label: "Design an email header set",
    seed: "Design a set of email headers in my brand style — one for the newsletter, one for promotions, one for plain updates.",
    tags: ["one-shot", "creative", "content"],
    weight: 0.5,
  },
  {
    id: "des-create-promo",
    department: "design",
    label: "Create a short promo video",
    seed: "Create a short promo video for my main offer. Lead with the outcome, keep it under thirty seconds, and end on where to go next.",
    tags: ["one-shot", "creative", "content"],
    weight: 1.0,
  },
  {
    id: "des-outline-rebrand",
    department: "design",
    label: "Outline a rebrand without the chaos",
    seed: "Outline what a rebrand would involve for my business — what changes, what stays, the order of operations, and how to do it without confusing customers.",
    tags: ["one-shot", "creative"],
    weight: 0.5,
  },
  {
    id: "des-design-packaging",
    department: "design",
    label: "Design packaging concepts",
    seed: "Design packaging concepts for my product. Make it shelf-recognizable, on brand, and practical to actually produce.",
    tags: ["one-shot", "creative", "ecommerce"],
    weight: 0.5,
  },
  {
    id: "des-create-icons",
    department: "design",
    label: "Create a custom icon set",
    seed: "Create a small custom icon set for my site and documents — one consistent style, sized for the places we'll actually use them.",
    tags: ["one-shot", "creative"],
    weight: 0.5,
  },
  {
    id: "des-review-readability",
    department: "design",
    label: "Review my site for easy reading",
    seed: "Review my site's type, contrast, and layout for readability. Flag what's hard to read on a phone in sunlight, and the fixes in order.",
    tags: ["one-shot", "creative", "compliance"],
    weight: 0.5,
  },
];
