/**
 * W44 — Finance outcome cards (20).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const financeOutcomeCards: OutcomeCard[] = [
  {
    id: "fin-forecast-cashflow",
    department: "finance",
    label: "Forecast next quarter's cash flow",
    seed: "Forecast my cash flow for next quarter. Work from what you know about my revenue and spending, and flag the months that look tight before they arrive.",
    tags: ["quarterly", "money"],
    weight: 1.5,
  },
  {
    id: "fin-draft-invoice",
    department: "finance",
    label: "Draft an invoice ready to send",
    seed: "Draft an invoice for recent work, ready to send. Use my standard terms and itemize it clearly enough that nobody emails back with questions.",
    tags: ["one-shot", "money"],
    weight: 1.5,
  },
  {
    id: "fin-review-pnl",
    department: "finance",
    label: "Review my P&L for the month",
    seed: "Review this month's profit and loss in plain language. Tell me what moved, why it moved, and the one line item that deserves my attention.",
    tags: ["monthly", "money"],
    weight: 1.5,
  },
  {
    id: "fin-build-budget",
    department: "finance",
    label: "Build next quarter's budget",
    seed: "Build a budget for next quarter from what you know about my spending and goals. Separate the must-spend from the nice-to-spend.",
    tags: ["quarterly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-map-expenses",
    department: "finance",
    label: "Map where my money actually goes",
    seed: "Map my spending by category and tell me where the money actually goes. Flag anything growing faster than revenue.",
    tags: ["monthly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-plan-taxes",
    department: "finance",
    label: "Plan my tax moves before year-end",
    seed: "Plan the tax moves I should consider before year-end. Base them on my business type and what you know about this year, and rank by likely savings.",
    tags: ["quarterly", "money", "compliance"],
    weight: 1.0,
  },
  {
    id: "fin-write-collections",
    department: "finance",
    label: "Write a firm but kind collections note",
    seed: "Write a collections message for an overdue invoice. Firm on the money, warm on the relationship, with a clear date and next step.",
    tags: ["one-shot", "money"],
    weight: 1.0,
  },
  {
    id: "fin-forecast-revenue",
    department: "finance",
    label: "Forecast revenue three ways",
    seed: "Forecast my revenue for the next two quarters in three scenarios — conservative, expected, and strong. Tell me what would have to be true for each.",
    tags: ["quarterly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-review-pricing",
    department: "finance",
    label: "Review my pricing against my costs",
    seed: "Review my pricing against my real costs. Show me the margin on each offer and where a price change would matter most.",
    tags: ["quarterly", "money", "revenue"],
    weight: 1.5,
  },
  {
    id: "fin-build-runway",
    department: "finance",
    label: "Build a runway model I can trust",
    seed: "Build a runway model for my business. Show me how many months we have at current burn, and what changes buy us more time.",
    tags: ["one-shot", "money"],
    weight: 1.0,
  },
  {
    id: "fin-outline-funding",
    department: "finance",
    label: "Outline my funding options",
    seed: "Outline the realistic funding options for a business my size — from credit lines to investors. Give me the true cost and trade-off of each.",
    tags: ["one-shot", "money"],
    weight: 0.5,
  },
  {
    id: "fin-draft-terms",
    department: "finance",
    label: "Draft payment terms that protect me",
    seed: "Draft payment terms for my client work. Protect my cash flow with deposits and due dates while staying easy to agree to.",
    tags: ["one-shot", "money", "service"],
    weight: 1.0,
  },
  {
    id: "fin-review-spend",
    department: "finance",
    label: "Review my recurring spend for cuts",
    seed: "Review everything my business pays for monthly. Flag what's unused, duplicated, or overpriced, and estimate what cutting it saves per year.",
    tags: ["quarterly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-build-scorecard",
    department: "finance",
    label: "Build a monthly money scorecard",
    seed: "Build a one-page monthly scorecard of the money numbers I should watch. Pick the five that matter for my business and define each in a sentence.",
    tags: ["monthly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-plan-margins",
    department: "finance",
    label: "Plan a path to higher margins",
    seed: "Plan how my business gets to healthier margins. Look at pricing, costs, and mix, and give me the three moves with the best effort-to-payoff ratio.",
    tags: ["one-shot", "money", "growth"],
    weight: 1.0,
  },
  {
    id: "fin-draft-quote",
    department: "finance",
    label: "Draft a quote for a new job",
    seed: "Draft a quote for a new job. Price it from what you know about my rates and costs, and present it so the value reads before the number does.",
    tags: ["one-shot", "money", "trades", "service"],
    weight: 0.5,
  },
  {
    id: "fin-review-receivables",
    department: "finance",
    label: "Review who owes me and how to collect",
    seed: "Review my outstanding receivables. Rank them by age and size, and give me a collection plan for each — from gentle reminder to final notice.",
    tags: ["monthly", "money"],
    weight: 1.0,
  },
  {
    id: "fin-forecast-hiring",
    department: "finance",
    label: "Forecast when I can afford to hire",
    seed: "Forecast when my business can afford its next hire. Show the full loaded cost and what revenue has to hold for the math to work.",
    tags: ["one-shot", "money", "people"],
    weight: 1.0,
  },
  {
    id: "fin-outline-valuation",
    department: "finance",
    label: "Outline what my business is worth",
    seed: "Outline a realistic valuation range for my business and what drives it. Tell me the two things that would raise the number most in a year.",
    tags: ["one-shot", "money"],
    weight: 0.5,
  },
  {
    id: "fin-build-reserve",
    department: "finance",
    label: "Build a cash reserve plan",
    seed: "Build a plan to put a real cash reserve in place. Set the target for a business like mine and the monthly amount that gets us there without starving growth.",
    tags: ["one-shot", "money"],
    weight: 0.5,
  },
];
