/**
 * W44 — Marketing outcome cards (25).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const marketingOutcomeCards: OutcomeCard[] = [
  {
    id: "mkt-write-blog",
    department: "marketing",
    label: "Write this week's blog post",
    seed: "Write this week's blog post in my brand voice. Pick the topic that best builds on our recent work and what my audience cares about right now.",
    tags: ["weekly", "content"],
    weight: 1.5,
  },
  {
    id: "mkt-plan-calendar",
    department: "marketing",
    label: "Plan a month of social content",
    seed: "Plan a month of social content for my business. Spread it across the platforms that matter to my audience and anchor it to what we're selling this month.",
    tags: ["monthly", "content"],
    weight: 1.5,
  },
  {
    id: "mkt-draft-newsletter",
    department: "marketing",
    label: "Draft this month's newsletter",
    seed: "Draft this month's newsletter in my voice. Lead with the most useful thing we did or learned recently, and end with one clear next step for readers.",
    tags: ["monthly", "content"],
    weight: 1.5,
  },
  {
    id: "mkt-write-captions",
    department: "marketing",
    label: "Write a week of social captions",
    seed: "Write a week of social captions for my business. Match my voice, vary the angles, and make each one stand alone for someone seeing us for the first time.",
    tags: ["weekly", "content"],
    weight: 1.0,
  },
  {
    id: "mkt-audit-seo",
    department: "marketing",
    label: "Audit my search visibility",
    seed: "Audit how my business shows up in search. Use what you know about my services and area, and tell me the three fixes that would move the needle fastest.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "mkt-outline-leadmagnet",
    department: "marketing",
    label: "Outline a lead magnet that converts",
    seed: "Outline a lead magnet my ideal customer would trade their email for. Base it on the problems we solve best and keep it something we can produce this week.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "mkt-write-linkedin",
    department: "marketing",
    label: "Write a LinkedIn post in my voice",
    seed: "Write a LinkedIn post in my voice. Pull from our recent work for the story, and end with a line that invites conversation rather than begging for it.",
    tags: ["weekly", "content", "b2b"],
    weight: 1.0,
  },
  {
    id: "mkt-plan-podcast",
    department: "marketing",
    label: "Plan a podcast episode",
    seed: "Plan a podcast episode for my show. Give me the angle, a segment outline, and the questions or talking points that keep it moving.",
    tags: ["one-shot", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-write-casestudy",
    department: "marketing",
    label: "Write a customer case study",
    seed: "Write a case study about a recent customer win. Use what you know about our work, structure it problem to result, and keep the numbers front and center.",
    tags: ["one-shot", "content", "b2b"],
    weight: 1.0,
  },
  {
    id: "mkt-draft-welcome",
    department: "marketing",
    label: "Draft a welcome email series",
    seed: "Draft a three-email welcome series for new signups. Introduce who we are, deliver something useful immediately, and make the next step obvious.",
    tags: ["one-shot", "content"],
    weight: 1.0,
  },
  {
    id: "mkt-write-landing",
    department: "marketing",
    label: "Write landing page copy that sells",
    seed: "Write landing page copy for my main offer. Lead with the outcome, handle the top objection, and close with one call to action.",
    tags: ["one-shot", "growth", "revenue"],
    weight: 1.5,
  },
  {
    id: "mkt-plan-launch",
    department: "marketing",
    label: "Plan a launch campaign",
    seed: "Plan a launch campaign for what we're releasing next. Map the two weeks around launch day across email and social, in my voice.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "mkt-write-reels",
    department: "marketing",
    label: "Write hooks for this week's Reels",
    seed: "Write ten short-video hooks for my business this week. Make each one specific to what we sell and strong enough to survive the first two seconds.",
    tags: ["weekly", "content", "b2c"],
    weight: 1.0,
  },
  {
    id: "mkt-refine-profiles",
    department: "marketing",
    label: "Refine my social profiles",
    seed: "Refine the bios and pinned content across my social profiles. Make every profile say what we do, who it's for, and why us — in my voice.",
    tags: ["one-shot", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-map-keywords",
    department: "marketing",
    label: "Map the words my buyers search",
    seed: "Map the search terms my buyers actually use. Group them by intent and tell me which ones our content should own first.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "mkt-write-thread",
    department: "marketing",
    label: "Write a thread from my best work",
    seed: "Write an X thread built from our best recent work. Open with a hook, teach something real in the middle, and land the ending.",
    tags: ["weekly", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-plan-youtube",
    department: "marketing",
    label: "Plan a YouTube video that ranks",
    seed: "Plan a YouTube video on the topic my audience searches most. Give me the title options, the hook, and a beat-by-beat outline.",
    tags: ["one-shot", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-generate-ideas",
    department: "marketing",
    label: "Generate 20 content ideas",
    seed: "Generate twenty content ideas grounded in what my customers ask, what we sell, and what's working in my industry right now. Rank them by likely payoff.",
    tags: ["monthly", "content"],
    weight: 1.5,
  },
  {
    id: "mkt-audit-citations",
    department: "marketing",
    label: "Audit where my brand gets cited",
    seed: "Audit where my business gets mentioned and cited online. Tell me where we're missing, where we're misrepresented, and what to fix first.",
    tags: ["quarterly", "growth"],
    weight: 0.5,
  },
  {
    id: "mkt-write-promo",
    department: "marketing",
    label: "Write a promo email for my next offer",
    seed: "Write a promotional email for my next offer. Make the value concrete, keep the urgency honest, and write it like me on a good day.",
    tags: ["one-shot", "revenue", "content"],
    weight: 1.0,
  },
  {
    id: "mkt-plan-carousel",
    department: "marketing",
    label: "Plan a carousel that earns saves",
    seed: "Plan a carousel post worth saving. Pick a topic we know cold, break it into slides that each earn the swipe, and write the caption.",
    tags: ["weekly", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-write-press",
    department: "marketing",
    label: "Write a press release worth printing",
    seed: "Write a press release about our latest news. Make the headline carry the story and keep the quotes sounding like a human said them.",
    tags: ["one-shot", "content"],
    weight: 0.5,
  },
  {
    id: "mkt-refine-voice",
    department: "marketing",
    label: "Refine my brand voice guide",
    seed: "Refine my brand voice into a one-page guide. Pull from how I actually write and talk, and give me do-and-don't examples my whole staff can follow.",
    tags: ["one-shot", "content"],
    weight: 1.0,
  },
  {
    id: "mkt-write-guestpitch",
    department: "marketing",
    label: "Write a podcast guest pitch",
    seed: "Write a pitch to get me booked as a podcast guest. Lead with what their audience gets, and propose three segment ideas I can deliver.",
    tags: ["one-shot", "growth"],
    weight: 0.5,
  },
  {
    id: "mkt-review-performance",
    department: "marketing",
    label: "Review last month's content results",
    seed: "Review how last month's content performed. Tell me what worked, what flopped, and the one change that matters most for next month.",
    tags: ["monthly", "content", "growth"],
    weight: 1.0,
  },
];
