/**
 * W44 — Operations outcome cards (25).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const operationsOutcomeCards: OutcomeCard[] = [
  {
    id: "ops-write-sop",
    department: "operations",
    label: "Write an SOP for a recurring task",
    seed: "Write an SOP for a task my business repeats every week. Make it step-by-step enough that someone new could follow it on day one.",
    tags: ["one-shot", "ops"],
    weight: 1.5,
  },
  {
    id: "ops-map-process",
    department: "operations",
    label: "Map a process end to end",
    seed: "Map one of my core processes end to end. Show every step and handoff, then mark where it slows down or breaks.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-build-checklist",
    department: "operations",
    label: "Build a launch-day checklist",
    seed: "Build a checklist for the next thing we're launching. Order it by when each item must happen and who owns it.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-plan-week",
    department: "operations",
    label: "Plan my team's week",
    seed: "Plan my team's week from what's on our plate. Sequence the work, protect time for the important-not-urgent, and flag what won't fit.",
    tags: ["weekly", "ops"],
    weight: 1.5,
  },
  {
    id: "ops-write-summary",
    department: "operations",
    label: "Write a one-page summary of the month",
    seed: "Write a one-page summary of the month for my own records. What we shipped, what slipped, what it means for next month.",
    tags: ["monthly", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-draft-agenda",
    department: "operations",
    label: "Draft a meeting agenda that ends on time",
    seed: "Draft an agenda for my next team meeting. Time-box each item, put decisions before discussions, and end with owners and dates.",
    tags: ["weekly", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-build-tracker",
    department: "operations",
    label: "Build a project tracker",
    seed: "Build a simple tracker for a project we're running. Milestones, owners, status, and the one risk per milestone worth watching.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-review-vendors",
    department: "operations",
    label: "Review my vendors for savings",
    seed: "Review the vendors my business depends on. Flag where we're overpaying or over-committed, and what to renegotiate first.",
    tags: ["quarterly", "ops", "money"],
    weight: 1.0,
  },
  {
    id: "ops-map-handoffs",
    department: "operations",
    label: "Map the handoffs that drop balls",
    seed: "Map where work gets handed off in my business and where it gets dropped. Suggest the lightest fix for each weak handoff.",
    tags: ["one-shot", "ops"],
    weight: 0.5,
  },
  {
    id: "ops-write-update",
    department: "operations",
    label: "Write a status update for stakeholders",
    seed: "Write a status update on our current work for the people who need to know. Progress, problems, and what we need from them — in that order.",
    tags: ["weekly", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-plan-quarter",
    department: "operations",
    label: "Plan the quarter's priorities",
    seed: "Plan the operational priorities for next quarter. Pick the few that compound, sequence them, and name what we're deliberately not doing.",
    tags: ["quarterly", "ops"],
    weight: 1.5,
  },
  {
    id: "ops-map-busywork",
    department: "operations",
    label: "Map the busywork I should hand off",
    seed: "Map the recurring busywork eating my week. Sort it into delegate, simplify, or stop — and write the handoff notes for the delegate pile.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-draft-brief",
    department: "operations",
    label: "Draft a project brief",
    seed: "Draft a brief for a project we're about to start. Goal, scope, owner, deadline, and what done looks like — one page, no filler.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-review-numbers",
    department: "operations",
    label: "Review this month's numbers in plain talk",
    seed: "Review this month's operational numbers in plain language. What's trending up, what's slipping, and the single chart I should care about.",
    tags: ["monthly", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-write-postmortem",
    department: "operations",
    label: "Write a postmortem without blame",
    seed: "Write a postmortem for something that went sideways. Stick to the timeline and causes, skip the blame, and end with changes we'll actually keep.",
    tags: ["one-shot", "ops"],
    weight: 0.5,
  },
  {
    id: "ops-plan-capacity",
    department: "operations",
    label: "Plan capacity for what's coming",
    seed: "Plan our capacity against what's coming in the next two months. Show me where we're overcommitted and the earliest date that bites.",
    tags: ["monthly", "ops", "people"],
    weight: 1.0,
  },
  {
    id: "ops-build-onboarding",
    department: "operations",
    label: "Build a client onboarding flow",
    seed: "Build the onboarding flow for a new client, from signed agreement to first delivered work. Every step, every email, every owner.",
    tags: ["one-shot", "ops", "service"],
    weight: 1.0,
  },
  {
    id: "ops-draft-scope",
    department: "operations",
    label: "Draft a scope of work",
    seed: "Draft a scope of work for an upcoming engagement. Be specific about deliverables and boundaries so changes become conversations, not surprises.",
    tags: ["one-shot", "ops", "service", "b2b"],
    weight: 1.0,
  },
  {
    id: "ops-review-risks",
    department: "operations",
    label: "Review the risks in my current plan",
    seed: "Review my current plans for the risks I'm not seeing. Rank them by likelihood and damage, and give me a cheap early-warning sign for each.",
    tags: ["quarterly", "ops"],
    weight: 0.5,
  },
  {
    id: "ops-write-faq",
    department: "operations",
    label: "Write an internal FAQ",
    seed: "Write an internal FAQ answering the questions my team asks me repeatedly. Pull from how we actually do things, and keep each answer under a paragraph.",
    tags: ["one-shot", "ops", "people"],
    weight: 0.5,
  },
  {
    id: "ops-map-supply",
    department: "operations",
    label: "Map my supply chain weak points",
    seed: "Map my supply chain and flag the single points of failure. For each weak point, give me a backup option and the trigger to switch.",
    tags: ["one-shot", "ops", "ecommerce"],
    weight: 0.5,
  },
  {
    id: "ops-plan-inventory",
    department: "operations",
    label: "Plan inventory for the season",
    seed: "Plan my inventory for the season ahead. Use what you know about my sales patterns, and flag what to order early and what to let run down.",
    tags: ["quarterly", "ops", "ecommerce", "restaurants"],
    weight: 0.5,
  },
  {
    id: "ops-build-template",
    department: "operations",
    label: "Build a reusable document template",
    seed: "Build a reusable template for a document my business produces over and over. Lock the structure, leave the variables obvious.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-outline-playbook",
    department: "operations",
    label: "Outline an operations playbook",
    seed: "Outline a playbook for how my business runs — the processes, standards, and decisions someone would need to run a day without me.",
    tags: ["one-shot", "ops"],
    weight: 1.0,
  },
  {
    id: "ops-write-actions",
    department: "operations",
    label: "Write up meeting notes into actions",
    seed: "Write up my rough meeting notes into a clean action list. Owner and due date on every line, decisions recorded at the top.",
    tags: ["weekly", "ops"],
    weight: 1.0,
  },
];
