/**
 * W44 — Paid Media outcome cards (20).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const paidMediaOutcomeCards: OutcomeCard[] = [
  {
    id: "pm-audit-adspend",
    department: "paid-media",
    label: "Audit my ad spend for waste",
    seed: "Audit my current ad spend for waste. Use what you know about my campaigns and goals, and show me where the budget leaks before suggesting anything new.",
    tags: ["one-shot", "growth", "money"],
    weight: 1.5,
  },
  {
    id: "pm-plan-campaign",
    department: "paid-media",
    label: "Plan a paid campaign from scratch",
    seed: "Plan a paid campaign for my main offer from scratch. Pick the channel that fits my audience and budget, and map the campaign structure before any copy.",
    tags: ["one-shot", "growth"],
    weight: 1.5,
  },
  {
    id: "pm-write-adcopy",
    department: "paid-media",
    label: "Write ad copy in three angles",
    seed: "Write ad copy for my offer in three distinct angles — pain, outcome, and proof. Keep each version tight enough for the platform it runs on.",
    tags: ["one-shot", "growth", "content"],
    weight: 1.5,
  },
  {
    id: "pm-build-audiences",
    department: "paid-media",
    label: "Build audiences worth paying for",
    seed: "Build the audience segments I should put money behind. Base them on who actually buys from us, and tell me which segment to test first.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-review-creative",
    department: "paid-media",
    label: "Review my ad creative before launch",
    seed: "Review my ad creative before it goes live. Score the hook, the clarity, and the call to action, and tell me what to fix in order of impact.",
    tags: ["one-shot", "creative", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-plan-split",
    department: "paid-media",
    label: "Plan my budget split across channels",
    seed: "Plan how my monthly ad budget should split across channels. Justify each share from what you know about my audience and results so far.",
    tags: ["monthly", "growth", "money"],
    weight: 1.0,
  },
  {
    id: "pm-draft-searchads",
    department: "paid-media",
    label: "Draft search ads for my best offers",
    seed: "Draft search ads for my best-performing offers. Match the headlines to what buyers actually type, and keep every line earning its place.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-write-hooks",
    department: "paid-media",
    label: "Write scroll-stopping ad hooks",
    seed: "Write ten ad hooks for my offer that survive the first second of a scroll. Vary the emotional angle and flag the two you'd test first.",
    tags: ["one-shot", "creative", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-map-funnel",
    department: "paid-media",
    label: "Map my paid funnel and its leaks",
    seed: "Map my paid funnel from impression to purchase. Show where people fall out, and rank the leaks by how much revenue fixing each would recover.",
    tags: ["one-shot", "growth", "revenue"],
    weight: 1.0,
  },
  {
    id: "pm-build-landingbrief",
    department: "paid-media",
    label: "Build a landing page brief for ads",
    seed: "Build a brief for the landing page my ads should point to. Match the message to the ad promise and structure the page for one decision.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-review-attribution",
    department: "paid-media",
    label: "Review what's actually driving sales",
    seed: "Review which marketing channels actually drive my sales. Tell me where attribution is lying to me and what to trust instead.",
    tags: ["quarterly", "growth", "revenue"],
    weight: 1.0,
  },
  {
    id: "pm-plan-retargeting",
    department: "paid-media",
    label: "Plan a retargeting push",
    seed: "Plan a retargeting push for the people who visited but didn't buy. Sequence the messages from reminder to reason to act now.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-audit-conversions",
    department: "paid-media",
    label: "Audit my conversion measurement",
    seed: "Audit how my conversions are measured. Flag what's double-counted, missing, or misattributed, and give me the fix list in order.",
    tags: ["one-shot", "growth", "compliance"],
    weight: 0.5,
  },
  {
    id: "pm-write-videoscript",
    department: "paid-media",
    label: "Write a video ad script",
    seed: "Write a thirty-second video ad script for my offer. Hook in the first two seconds, one message in the middle, one action at the end.",
    tags: ["one-shot", "creative", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-forecast-returns",
    department: "paid-media",
    label: "Forecast returns on next month's spend",
    seed: "Forecast what next month's ad spend should return. Use my numbers where you have them, state your assumptions, and give me a range, not one number.",
    tags: ["monthly", "growth", "money"],
    weight: 0.5,
  },
  {
    id: "pm-plan-test",
    department: "paid-media",
    label: "Plan an ad test worth running",
    seed: "Plan one ad test that would teach us the most right now. Define the variant, the success line, and how long to run it before judging.",
    tags: ["one-shot", "growth"],
    weight: 1.0,
  },
  {
    id: "pm-draft-socialads",
    department: "paid-media",
    label: "Draft paid social variations",
    seed: "Draft three variations of a paid social ad for my offer — different opening, same destination. Note which audience each fits best.",
    tags: ["one-shot", "growth", "content"],
    weight: 1.0,
  },
  {
    id: "pm-review-searchterms",
    department: "paid-media",
    label: "Review my search terms for waste",
    seed: "Review the search terms my ads show up for. Flag what's irrelevant and draining budget, and build the exclusion list to stop it.",
    tags: ["monthly", "growth", "money"],
    weight: 0.5,
  },
  {
    id: "pm-outline-launchplan",
    department: "paid-media",
    label: "Outline a paid launch plan",
    seed: "Outline the paid side of our next launch. Phase the spend from warm-up to launch week to follow-through, with a budget for each phase.",
    tags: ["one-shot", "growth"],
    weight: 0.5,
  },
  {
    id: "pm-build-report",
    department: "paid-media",
    label: "Build a monthly paid media report",
    seed: "Build a monthly report on my paid results that I can read in five minutes. Spend, returns, what changed, and what we change next.",
    tags: ["monthly", "growth"],
    weight: 1.0,
  },
];
