/**
 * W44 — Sales outcome cards (20).
 * Voice-locked per BRAND_VOICE.md: verb-first, operator-to-staff, no
 * specialist names, no tool jargon. Seeds pull vault context implicitly.
 */

import type { OutcomeCard } from "./types";

export const salesOutcomeCards: OutcomeCard[] = [
  {
    id: "sal-draft-coldemail",
    department: "sales",
    label: "Draft cold outreach to a new prospect",
    seed: "Draft a cold outreach email to a new prospect. Lead with the outcome my business delivers, keep it short enough to read on a phone, and end with one easy ask.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 1.5,
  },
  {
    id: "sal-write-followup",
    department: "sales",
    label: "Write a follow-up that revives a deal",
    seed: "Write a follow-up for a deal that's gone quiet. Add something useful instead of just checking in, and give them an easy way to re-engage.",
    tags: ["one-shot", "revenue"],
    weight: 1.5,
  },
  {
    id: "sal-draft-proposal",
    department: "sales",
    label: "Draft a proposal for an open deal",
    seed: "Draft a proposal for a deal I'm working. Use what you know about my services and pricing, and structure it so the decision is easy to say yes to.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 1.5,
  },
  {
    id: "sal-build-sequence",
    department: "sales",
    label: "Build a 5-touch outreach sequence",
    seed: "Build a five-touch outreach sequence for my ideal customer. Vary the channel and angle each touch, and keep every message worth opening on its own.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 1.0,
  },
  {
    id: "sal-review-pipeline",
    department: "sales",
    label: "Review my pipeline for stuck deals",
    seed: "Review my open deals and flag the ones going stale. For each stuck deal, tell me the likely reason and the next move to unstick it.",
    tags: ["weekly", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-write-rfp",
    department: "sales",
    label: "Write an RFP response",
    seed: "Write a response to an RFP I'm pursuing. Use what you know about our strengths, answer what they actually asked, and make our difference impossible to miss.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 0.5,
  },
  {
    id: "sal-plan-discovery",
    department: "sales",
    label: "Plan questions for a discovery call",
    seed: "Plan my next discovery call. Give me the questions that uncover budget, urgency, and the real problem — in an order that feels like a conversation.",
    tags: ["one-shot", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-draft-pricing",
    department: "sales",
    label: "Draft a pricing conversation script",
    seed: "Draft how I should walk a prospect through my pricing. Anchor on value first, and give me responses for the two pushbacks I hear most.",
    tags: ["one-shot", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-write-objections",
    department: "sales",
    label: "Write answers to my top objections",
    seed: "Write strong answers to the objections I hear most often. Use what you know about my offer, and make each answer honest enough to say with a straight face.",
    tags: ["one-shot", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-map-accounts",
    department: "sales",
    label: "Map my top accounts for expansion",
    seed: "Map my best existing customers for expansion. Tell me who has room to grow with us, what to offer each one, and how to open the conversation.",
    tags: ["quarterly", "revenue", "b2b"],
    weight: 1.0,
  },
  {
    id: "sal-draft-renewal",
    department: "sales",
    label: "Draft a renewal outreach",
    seed: "Draft a renewal message for a customer coming up on their term. Remind them of the value delivered with specifics, and make renewing the easy path.",
    tags: ["one-shot", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-draft-connects",
    department: "sales",
    label: "Draft connection notes that land",
    seed: "Draft short LinkedIn connection notes for the people I want to meet. Make each one specific to why them, without a pitch in the first message.",
    tags: ["weekly", "revenue", "b2b"],
    weight: 0.5,
  },
  {
    id: "sal-build-battlecard",
    department: "sales",
    label: "Build a battlecard for a rival offer",
    seed: "Build a battlecard against the alternative my prospects compare us to. Where we win, where we're weaker, and exactly what to say in each case.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 0.5,
  },
  {
    id: "sal-outline-demo",
    department: "sales",
    label: "Outline a demo that closes",
    seed: "Outline my next demo around the customer's problem, not our menu of capabilities. Build to one moment that makes the value land, then ask for the business.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 1.0,
  },
  {
    id: "sal-write-breakup",
    department: "sales",
    label: "Write a breakup email for a cold deal",
    seed: "Write a respectful final email for a deal that won't engage. Close the loop, leave the door open, and sometimes that's the message that gets the reply.",
    tags: ["one-shot", "revenue"],
    weight: 0.5,
  },
  {
    id: "sal-forecast-quarter",
    department: "sales",
    label: "Forecast this quarter's sales",
    seed: "Forecast my sales for this quarter from what you know about my pipeline and history. Show me the committed, likely, and stretch numbers separately.",
    tags: ["quarterly", "revenue", "money"],
    weight: 1.0,
  },
  {
    id: "sal-draft-expansion",
    department: "sales",
    label: "Draft an expansion pitch for a client",
    seed: "Draft a pitch that grows an existing client relationship. Ground it in results we've already delivered them and one specific next win.",
    tags: ["one-shot", "revenue", "b2b"],
    weight: 1.0,
  },
  {
    id: "sal-review-call",
    department: "sales",
    label: "Review my last sales call",
    seed: "Review my notes from my last sales call. Tell me what I handled well, what I missed, and the exact follow-up to send today.",
    tags: ["one-shot", "revenue"],
    weight: 1.0,
  },
  {
    id: "sal-write-referral",
    department: "sales",
    label: "Write a referral ask that feels easy",
    seed: "Write a referral ask for my happiest customers. Make it effortless to forward and specific about who we help best.",
    tags: ["one-shot", "revenue", "growth"],
    weight: 1.0,
  },
  {
    id: "sal-plan-territory",
    department: "sales",
    label: "Plan this month's outreach focus",
    seed: "Plan where my outreach time goes this month. Pick the segments worth the effort, set weekly targets, and tell me what to stop chasing.",
    tags: ["monthly", "revenue"],
    weight: 1.0,
  },
];
